#!/usr/bin/env bash
executor=$(which manticore-executor 2> /dev/null)
if [[ -z "$executor" ]]; then
  echo >&2 __NAME__  requires manticore-executor. Please install package 'manticore-extra'.
  exit 1
fi

tmp=$($executor -r 'echo sys_get_temp_dir();')
php_file="$tmp"/__PACKAGE__.phar
self_ts=$(date -r "$0" +%s)
phar_ts=$(test -f "$php_file" && date -r "$_" +%s || echo 0)
test "$self_ts" -gt "$phar_ts" && echo '<?php file_put_contents("'"$php_file"'", hex2bin("__CONTENT_HEX__"));' | $executor
exec $executor -n "$php_file" "$@"
